# Generated by Django 3.1.7 on 2021-04-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210402_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
