# Generated by Django 3.1.7 on 2021-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.TextField(unique=True),
        ),
    ]
