# Generated by Django 3.1.7 on 2021-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210405_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=11, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=1, upload_to='media1/'),
            preserve_default=False,
        ),
    ]
