# Generated by Django 3.1.7 on 2021-04-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210408_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='image',
            new_name='photo',
        ),
    ]
